import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useEffect } from 'react';
import {
	Button,
	Grid,
	GridItem,
	Heading,
	Image,
	Text,
	useDisclosure,
	useToast,
} from '@chakra-ui/react';
import LoginModal from '../components/modals/LoginModal';
import { useConnect } from 'wagmi';

const Home: NextPage = () => {
	const onConnect = () => {
		// This library doesn't work correctly with Next.js.
		// Connectors are not loaded with useRouter.
		window.location.replace('/stake');
	};

	const toast = useToast();
	const onError = (error: Error) => {
		toast({
			title: error.name,
			description: error.message,
			status: 'error',
			duration: 5000,
			isClosable: true,
		});
	};

	const { connect, connectors, isConnecting, isConnected } = useConnect({
		onConnect,
		onError,
	});

	useEffect(() => {
		if (isConnected) {
			window.location.replace('/stake');
		}
	}, [isConnected]);

	const { isOpen, onOpen, onClose } = useDisclosure();

	return (
		<>
			<Head>
				<title>Fake NFT - </title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<LoginModal
				title="Connect your wallet"
				isOpen={isOpen}
				onClose={onClose}
				connectors={connectors}
				onClick={connect}
				isLoading={isConnecting}
			/>
			<Grid
				height="100vh"
				templateAreas={{
					base: '"bg" "info"',
				}}
				templateColumns={{
					base: '1fr',
				}}
				templateRows={{
					base: '2fr 1fr',
				}}
			>
				<Image
					height="100%"
					objectFit="cover"
					src="/backgrounds/home.png"
					alt="Home background"
				/>
				<GridItem padding={4}>
					<Heading as="h1" size="2xl">
						Fake NFT
					</Heading>
					<Text paddingBottom={8}>
						Play awesome games and earn coins along the way
					</Text>
					<Button variant="solid" width="100%" onClick={onOpen}>
						Let&#39;s go!
					</Button>
				</GridItem>
			</Grid>
		</>
	);
};

export default Home;
