import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useEffect } from 'react';
import {
	Button,
	Grid,
	GridItem,
	Heading,
	Image,
	Text,
	useDisclosure,
	useToast,
} from '@chakra-ui/react';
import LoginModal from '../components/modals/LoginModal';
import { useConnect } from 'wagmi';

const Home: NextPage = () => {
	const onConnect = () => {
		// This library doesn't work correctly with Next.js.
		// Connectors are not loaded with useRouter.
		window.location.replace('/stake');
	};

	const toast = useToast();
	const onError = (error: Error) => {
		toast({
			title: error.name,
			description: error.message,
			status: 'error',
			duration: 5000,
			isClosable: true,
		});
	};

	const { connect, connectors, isConnecting, isConnected } = useConnect({
		onConnect,
		onError,
	});

	useEffect(() => {
		if (isConnected) {
			window.location.replace('/stake');
		}
	}, [isConnected]);

	const { isOpen, onOpen, onClose } = useDisclosure();

	return (
		<>
			<Head>
				<title>Fake NFT - </title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<LoginModal
				title="Connect your wallet"
				isOpen={isOpen}
				onClose={onClose}
				connectors={connectors}
				onClick={connect}
				isLoading={isConnecting}
			/>
			<Grid
				height="100vh"
				templateAreas={{
					base: '"bg" "info"',
					lg: '"info bg"',
				}}
				templateColumns={{
					base: '1fr',
					lg: '1fr 2fr',
				}}
				templateRows={{
					base: '2fr 1fr',
					lg: 'auto 1fr',
				}}
			>
				<GridItem area="bg" justifySelf="center" alignSelf="center">
					<Image
						height="100%"
						maxHeight="100vh"
						objectFit="cover"
						src="/backgrounds/home.png"
						alt="Home background"
					/>
				</GridItem>
				<GridItem
					area="info"
					paddingTop={12}
					paddingX={4}
					paddingBottom={16}
					alignSelf={{
						base: 'end',
						lg: 'center',
					}}
				>
					<Heading as="h1" size="2xl">
						Fake NFT
					</Heading>
					<Text paddingBottom={8}>
						Play awesome games and earn coins along the way
					</Text>
					<Button variant="solid" width="100%" onClick={onOpen}>
						Let&#39;s go!
					</Button>
				</GridItem>
			</Grid>
		</>
	);
};

export default Home;
